all:
  hosts:
    pannu01:
      ansible_host: 95.216.207.125
    pannu02:
      ansible_host: 95.216.143.33
    pannu03:
      ansible_host: 95.216.143.26
    pannu04:
      ansible_host: 95.216.207.110
    pannu05:
      ansible_host: 95.216.143.29
    pannu06:
      ansible_host: 95.216.207.140
    pannu07:
      ansible_host: 95.216.143.32
    pannu08:
      ansible_host: 95.216.143.28
    pannu09:
      ansible_host: 95.216.143.31
    pannu10:
      ansible_host: 95.216.143.30
  children:
    ksyk:
      hosts:
        pannu01:
        pannu02:
        pannu03:
        pannu04:
        pannu05:
        pannu06:
        pannu07:
    otaniemi:
      hosts:
        pannu08:
        pannu09:
        pannu10:
  vars:
    ansible_ssh_user: root
