all:
  hosts:
    pannu0:
      ansible_host: 95.216.207.125
    pannu1:
      ansible_host: 95.216.143.33
    pannu2:
      ansible_host: 95.216.143.26
    pannu3:
      ansible_host: 95.216.207.110
    pannu4:
      ansible_host: 95.216.143.29
    pannu5:
      ansible_host: 95.216.207.140
    pannu6:
      ansible_host: 95.216.143.32
    pannu7:
      ansible_host: 95.216.143.28
    pannu8:
      ansible_host: 95.216.143.31
    pannu9:
      ansible_host: 95.216.143.30
  children:
    ksyk:
      hosts:
        pannu0:
        pannu1:
        pannu2:
        pannu3:
        pannu4:
        pannu5:
        pannu6:
    otaniemi:
      hosts:
        pannu7:
        pannu8:
        pannu9:
  vars:
    ansible_ssh_user: root
