- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - include_tasks: ssh_gen_key.yml
      loop: "{{ groups.all }}"

- hosts: all
  gather_facts: yes
  tasks:
    - name: Update system
      ansible.builtin.apt:
        update_cache: yes
        upgrade: full

    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    
    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true
        
    # - name: Wait for system to become reachable again
    #   wait_for_connection:
    #     delay: 5
    #     timeout: 300

    - name: Install Fish shell
      ansible.builtin.apt:
        name:
          - fish

    - name: Create koodi101 user
      ansible.builtin.user:
        name: koodi101
        uid: 1000
        shell: /usr/bin/fish
        group: sudo

    - name: Set SSH keys for the user
      ansible.builtin.authorized_key:
        user: koodi101
        key: "{{ lookup('file', './ssh_keys/id_rsa_koodi101_' + inventory_hostname + '.pub') }}"
        state: present

    - name: Add koodi101 to sudoers without password
      community.general.sudoers:
        name: koodi101
        user: koodi101
        commands: ALL
        nopassword: true
