- hosts: all
  gather_facts: yes
  tasks:
    - name: Update system
      ansible.builtin.apt:
        update_cache: yes
        upgrade: full


    - name: Reboot box if kernel/libs updated and requested by the system
      shell: /sbin/shutdown -r now
      args:
        removes: /var/run/reboot-required
      async: 300
      poll: 0
      ignore_errors: true
    
    - name: Wait for system to become reachable again
      wait_for_connection:
        delay: 5
        timeout: 300

    - name: Install Fish shell
      ansible.builtin.apt:
        name:
          - fish

    - name: Create koodi101 user
      ansible.builtin.user:
        name: koodi101
        uid: 1000
        shell: /usr/bin/fish
        group: sudo

    - include_tasks: ssh_gen_key.yml
      loop: "{{ groups.all }}"
